#!/bin/bash
# Copyright (C) 2019 Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
# postfix filter script for gpgmail
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

USAGE="Usage: $0 (gnupghome=PATH) -oi -f SENDER RECIPIENT ARGS"
if [ "$#" == "0" ]; then
    echo "$USAGE"
    exit 1
fi

SENDMAIL=/usr/sbin/sendmail
GPGMAIL=/usr/bin/gpgmail
set -o pipefail

#encrypt and resend directly from stdin
if [[ ${1:0:10} == "gnupghome=" ]]; then
    GNUPGHOME=${1:10}
    shift

    ${GPGMAIL} --gnupghome $GNUPGHOME -e "$4" | ${SENDMAIL} "$@"
else
    ${GPGMAIL} -e "$4" | ${SENDMAIL} "$@"
fi

exit $?
